
server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.ca0okwo8st6n.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929-youri?allowMultiQueries=true
    #?allowMultiQueries=true 는 Insert into가 두번 가능
    username: admin
    password: 1q2w3e4r

  security:
    user:
      name: youri
      password: 1q2w3e4r!
    oauth2:
      client:
        registration:
          google:
            clientId: 788533265155-72k6eis0r76cko89fum3mlg6fboumfqp.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:\Korea IT\web\springboot\stussy-clone-20220929-youri/upload/
